# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZWMzNDBlOTRhZDFlMDk3YTg4Mzc0YjFjNGNlZjNmYjBjNWI1YWJlOTkzZWY4NTY5ZjlmYzU4MDUwYWQ0YTgwY2YyNTRmOTc4YTM5ODZiMzIzMzc1ZjgyODA2Mzc3OGZkMGQzMDY4NTZhNDczY2Y2Y2QyOTE4YjUyZTZjNzZjYmM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
